export const allPlayerFields = `{
    _id,
    displayName,
    fullName,
    "profile": profile.asset->url,
    goals,
    points,
    footballAssists,
    basketballAssists,
    steals,
    blocks,
    rebounds,
    fouls,
    redCards,
    yellowCards,
    number,
    position,
    gender,
    }`;
